[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build]
  base = "client"
  publish = "client/dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.20.3"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
