[build]
  publish = "public"
  command = "npm run build"  # Si vous avez un build step

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200