[build]
  publish = "public"
  command = "npm run build"
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200