[build]
  publish = "public"  # Main site files
  command = "npm run build && cp -r admin/public public/admin"

[functions]
  directory = "admin/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200