[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build]
  publish = "public"  # Best practice - only publish what's needed
  command = "npm run build"  # Add your build command if you have one

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
