[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build]
  publish = "public"  # مجلد الملفات النهائي
  command = ""        # لا حاجة لأمر build

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/admin"
  status = 200
